const COUNTRY_TAG = {
    "AF": "Afghanistan",
    "AX": "Åland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cabo Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo (Democratic Republic of the)",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Côte d'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CW": "Curaçao",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and McDonald Islands",
    "VA": "Holy See",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea (Democratic People's Republic of)",
    "KR": "Korea (Republic of)",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People's Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "North Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestine, State of",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint Barthélemy",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin (French part)",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SX": "Sint Maarten (Dutch part)",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen",
    "SZ": "Eswatini",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom of Great Britain and Northern Ireland",
    "US": "United States of America",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela (Bolivarian Republic of)",
    "VN": "Viet Nam",
    "VG": "Virgin Islands (British)",
    "VI": "Virgin Islands (U.S.)",
    "WF": "Wallis and Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
  }
  
  const COUNTRY_TIMEZONE = {
"Afghanistan": "Asia/Kabul" ,
"Albania": "Europe/Tirane" ,
"Algeria": "Africa/Algiers" ,
"Andorra": "Europe/Andorra" ,
"Angola": "Africa/Luanda" ,
"Antigua and Barbuda": "America/Antigua" ,
"Argentina": "America/Argentina/Buenos_Aires" ,
"Armenia": "Asia/Yerevan" ,
"Australia": "Australia/Sydney" ,
"Austria": "Europe/Vienna" ,
"Azerbaijan": "Asia/Baku" ,
"Bahamas": "America/Nassau" ,
"Bahrain": "Asia/Bahrain" ,
"Bangladesh": "Asia/Dhaka" ,
"Barbados": "America/Barbados" ,
"Belarus": "Europe/Minsk" ,
"Belgium": "Europe/Brussels" ,
"Belize": "America/Belize" ,
"Benin": "Africa/Porto-Novo" ,
"Bhutan": "Asia/Thimphu" ,
"Bolivia": "America/La_Paz" ,
"Bosnia and Herzegovina": "Europe/Sarajevo" ,
"Botswana": "Africa/Gaborone" ,
"Brazil": "America/Sao_Paulo" ,
"Brunei": "Asia/Brunei" ,
"Bulgaria": "Europe/Sofia" ,
"Burkina Faso": "Africa/Ouagadougou" ,
"Burundi": "Africa/Bujumbura" ,
"Cambodia": "Asia/Phnom_Penh" ,
"Cameroon": "Africa/Douala" ,
"Canada": "America/Toronto" ,
"Cape Verde": "Atlantic/Cape_Verde" ,
"Central African Republic": "Africa/Bangui" ,
"Chad": "Africa/Ndjamena" ,
"Chile": "America/Santiago" ,
"China": "Asia/Shanghai" ,
"Colombia": "America/Bogota" ,
"Comoros": "Indian/Comoro" ,
"Congo": "Africa/Brazzaville" ,
"Costa Rica": "America/Costa_Rica" ,
"Croatia": "Europe/Zagreb" ,
"Cuba": "America/Havana" ,
"Cyprus": "Asia/Nicosia" ,
"Czech Republic": "Europe/Prague" ,
"Denmark": "Europe/Copenhagen" ,
"Djibouti": "Africa/Djibouti" ,
"Dominica": "America/Dominica" ,
"Dominican Republic": "America/Santo_Domingo" ,
"East Timor": "Asia/Dili" ,
"Ecuador": "America/Guayaquil" ,
"Egypt": "Africa/Cairo" ,
"El Salvador": "America/El_Salvador" ,
"Equatorial Guinea": "Africa/Malabo" ,
"Eritrea": "Africa/Asmara" ,
"Estonia": "Europe/Tallinn" ,
"Ethiopia": "Africa/Addis_Ababa" ,
"Fiji": "Pacific/Fiji" ,
"Finland": "Europe/Helsinki" ,
"France": "Europe/Paris" ,
"Gabon": "Africa/Libreville" ,
"Gambia": "Africa/Banjul" ,
"Georgia": "Asia/Tbilisi" ,
"Germany": "Europe/Berlin" ,
"Ghana": "Africa/Accra" ,
"Greece": "Europe/Athens" ,
"Grenada": "America/Grenada" ,
"Guatemala": "America/Guatemala" ,
"Guinea": "Africa/Conakry" ,
"Guinea-Bissau": "Africa/Bissau" ,
"Guyana": "America/Guyana" ,
"Haiti": "America/Port-au-Prince" ,
"Honduras": "America/Tegucigalpa" ,
"Hungary": "Europe/Budapest" ,
"Iceland": "Atlantic/Reykjavik" ,
"India": "Asia/Kolkata" ,
"Indonesia": "Asia/Jakarta" ,
"Iran": "Asia/Tehran" ,
"Iraq": "Asia/Baghdad" ,
"Ireland": "Europe/Dublin" ,
"Israel": "Asia/Jerusalem" ,
"Italy": "Europe/Rome" ,
"Jamaica": "America/Jamaica" ,
"Japan": "Asia/Tokyo" ,
"Jordan": "Asia/Amman" ,
"Kazakhstan": "Asia/Almaty" ,
"Kenya": "Africa/Nairobi" ,
"Kiribati": "Pacific/Tarawa" ,
"Korea, North": "Asia/Pyongyang" ,
"Korea, South": "Asia/Seoul" ,
"Kuwait": "Asia/Kuwait" ,
"Kyrgyzstan": "Asia/Bishkek" ,
"Laos": "Asia/Vientiane" ,
"Latvia": "Europe/Riga" ,
"Lebanon": "Asia/Beirut" ,
"Lesotho": "Africa/Maseru" ,
"Liberia": "Africa/Monrovia" ,
"Libya": "Africa/Tripoli" ,
"Liechtenstein": "Europe/Vaduz" ,
"Lithuania": "Europe/Vilnius" ,
"Luxembourg": "Europe/Luxembourg" ,
"Macedonia": "Europe/Skopje" ,
"Madagascar": "Indian/Antananarivo" ,
"Malawi": "Africa/Blantyre" ,
"Malaysia": "Asia/Kuala_Lumpur" ,
"Maldives": "Indian/Maldives" ,
"Mali": "Africa/Bamako" ,
"Malta": "Europe/Malta" ,
"Marshall Islands": "Pacific/Majuro" ,
"Mauritania": "Africa/Nouakchott" ,
"Mauritius": "Indian/Mauritius" ,
"Mexico": "America/Mexico_City" ,
"Micronesia": "Pacific/Pohnpei" ,
"Moldova": "Europe/Chisinau" ,
"Monaco": "Europe/Monaco" ,
"Mongolia": "Asia/Ulaanbaatar" ,
"Montenegro": "Europe/Podgorica" ,
"Morocco": "Africa/Casablanca" ,
"Mozambique": "Africa/Maputo" ,
"Myanmar": "Asia/Yangon" ,
"Namibia": "Africa/Windhoek" ,
"Nauru": "Pacific/Nauru" ,
"Nepal": "Asia/Kathmandu" ,
"Netherlands": "Europe/Amsterdam" ,
"New Zealand": "Pacific/Auckland" ,
"Nicaragua": "America/Managua" ,
"Niger": "Africa/Niamey" ,
"Nigeria": "Africa/Lagos" ,
"Norway": "Europe/Oslo" ,
"Oman": "Asia/Muscat" ,
"Pakistan": "Asia/Karachi" ,
"Palau": "Pacific/Palau" ,
"Panama": "America/Panama" ,
"Papua New Guinea": "Pacific/Port_Moresby" ,
"Paraguay": "America/Asuncion" ,
"Peru": "America/Lima" ,
"Philippines": "Asia/Manila" ,
"Poland": "Europe/Warsaw" ,
"Portugal": "Europe/Lisbon" ,
"Qatar": "Asia/Qatar" ,
"Romania": "Europe/Bucharest" ,
"Russia": "Europe/Moscow" ,
"Rwanda": "Africa/Kigali" ,
"Saint Kitts and Nevis": "America/St_Kitts" ,
"Saint Lucia": "America/St_Lucia" ,
"Saint Vincent and the Grenadines": "America/St_Vincent" ,
"Samoa": "Pacific/Apia" ,
"San Marino": "Europe/San_Marino" ,
"Sao Tome and Principe": "Africa/Sao_Tome" ,
"Saudi Arabia": "Asia/Riyadh" ,
"Senegal": "Africa/Dakar" ,
"Serbia": "Europe/Belgrade" ,
"Seychelles": "Indian/Mahe" ,
"Sierra Leone": "Africa/Freetown" ,
"Singapore": "Asia/Singapore" ,
"Slovakia": "Europe/Bratislava" ,
"Slovenia": "Europe/Ljubljana" ,
"Solomon Islands": "Pacific/Guadalcanal" ,
"Somalia": "Africa/Mogadishu" ,
"South Africa": "Africa/Johannesburg" ,
"South Sudan": "Africa/Juba" ,
"Spain": "Europe/Madrid" ,
"Sri Lanka": "Asia/Colombo" ,
"Sudan": "Africa/Khartoum" ,
"Suriname": "America/Paramaribo" ,
"Swaziland": "Africa/Mbabane" ,
"Sweden": "Europe/Stockholm" ,
"Switzerland": "Europe/Zurich" ,
"Syria": "Asia/Damascus" ,
"Taiwan": "Asia/Taipei" ,
"Tajikistan": "Asia/Dushanbe" ,
"Tanzania": "Africa/Dar_es_Salaam" ,
"Thailand": "Asia/Bangkok" ,
"Togo": "Africa/Lome" ,
"Tonga": "Pacific/Tongatapu" ,
"Trinidad and Tobago": "America/Port_of_Spain" ,
"Tunisia": "Africa/Tunis" ,
"Turkey": "Europe/Istanbul" ,
"Turkmenistan": "Asia/Ashgabat" ,
"Tuvalu": "Pacific/Funafuti" ,
"Uganda": "Africa/Kampala" ,
"Ukraine": "Europe/Kiev" ,
"United Arab Emirates": "Asia/Dubai" ,
"United Kingdom": "Europe/London" ,
"United States": "America/New_York" ,
"Uruguay": "America/Montevideo" ,
"Uzbekistan": "Asia/Tashkent" ,
"Vanuatu": "Pacific/Efate" ,
"Vatican City": "Europe/Vatican" ,
"Venezuela": "America/Caracas" ,
"Vietnam": "Asia/Ho_Chi_Minh" ,
"Yemen": "Asia/Aden" ,
"Zambia": "Africa/Lusaka" ,
"Zimbabwe": "Africa/Harare",
}